server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  expiration:
    access: ${JWT_ACCESS_EXPIRATION}
    refresh: ${JWT_REFRESH_EXPIRATION}
  rsa:
    private-key: ${JWT_RSA_PRIVATE_KEY}

internal:
  gateway-secret: ${INTERNAL_GATEWAY_SECRET}