server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bds_member_prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate