spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    virtual-host: ${RABBITMQ_VHOST:msa}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    publisher-confirm-type: correlated
    publisher-returns: true

  modulith:
    events:
      externalization:
        enabled: true
      republish-outstanding-events-on-restart: false
      staleness:
        published: 1m
        processing: 5m
        resubmitted: 2m
bds:
  messaging:
    events:
      republish-delay: 30s
      republish-min-age: 1m
      retention: 7d

logging:
  level:
    com.bds.payment: DEBUG
    org.hibernate.SQL: DEBUG

bank:
  api:
    base-url: ${BANK_URL}

internal:
  gateway-secret: ${INTERNAL_GATEWAY_SECRET:local-dev-internal-secret}