spring:
  application:
    name: order-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    virtual-host: msa
    username: ${RABBITMQ_USER:order-service}
    password: ${RABBITMQ_PASSWORD:order1234}
    # 발행 서비스 필수 — confirm 콜백이 동작하기 위한 설정
    publisher-confirm-type: correlated
    publisher-returns: true

  modulith:
    events:
      externalization:
        enabled: true
      #        mode: outbox
      republish-outstanding-events-on-restart: false
      staleness: #Fail 기준
        published: 1m
        processing: 5m
        resubmitted: 2m

bds:
  messaging:
    events:
      republish-delay: 30s
      republish-min-age: 1m
      retention: 7d

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: ${SERVER_PORT:8080}
