spring:
  application:
    name: chat-service
  datasource:
    hikari:
      connection-timeout: 5000
  jackson:
    time-zone: UTC
    datatype:
      datetime:
        write-dates-as-timestamps: false
  task:
    scheduling:
      shutdown:
        await-termination: true
        await-termination-period: 10s

chat:
  read:
    flush-interval-ms: 10000  # 읽음 처리 버퍼 flush 주기 (ms)

server:
  port: 8082
# grafana monitoring
#  tomcat:
#    mbeanregistry:
#      enabled: true
