spring:
  profiles:
    active: dev
  application:
    name: notification-service

  flyway:
    enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8083