definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/generated/definitions.json

# 디스크 여유 공간 알람 기준
disk_free_limit.absolute = 2GB

# 메모리 워터마크
vm_memory_high_watermark.relative = 0.6
