name: CI - auth-service

# auth-service 디렉토리 변경 시에만 실행
on:
  push:
    branches: [main, develop]
    paths:
      - 'services/auth-service/**'
  pull_request:
    branches: [develop]
    paths:
      - 'services/auth-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # 1. PostgreSQL
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: auth_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      # 2. Redis
      redis:
        image: redis:8
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            services/auth-service
            modules/common
            build.gradle
            settings.gradle
            gradlew
            gradle

      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew :services:auth-service:clean :services:auth-service:build :services:auth-service:jacocoTestReport --stacktrace -Dspring.profiles.active=dev

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth-service
          path: services/auth-service/build/libs/*[!plain].jar

      - name: Upload Auth Service Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-auth-report
          path: services/auth-service/build/reports/jacoco/test/html/
