name: CI - notification-service

# notification-service 디렉토리 변경 시에만 실행
on:
  push:
    branches: [main, develop]
    paths:
      - 'services/notification-service/**'
  pull_request:
    branches: [develop]
    paths:
      - 'services/notification-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # TODO: notification-service DB 확정 후 추가
    # ex) mysql, postgresql 등

    # 예시
#    services:
#      # SSE 미접속 유저 대상 FCM 대체 발송 및 토픽 구독 처리에 사용
#      redis:
#        image: redis:8
#        ports:
#          - 6379:6379
#        options: >-
#          --health-cmd "redis-cli ping"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5



    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            services/notification-service
            modules/common
            build.gradle
            settings.gradle
            gradlew
            gradle

      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew :services:notification-service:clean :services:notification-service:build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: notification-service
          path: services/notification-service/build/libs/*[!plain].jar
